services:
  expo:
    build: .
    ports:
      - "8081:8081"
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    environment:
      EXPO_DEVTOOLS_LISTEN_ADDRESS: "0.0.0.0"
      EXPO_NO_TELEMETRY: "1"
      CHOKIDAR_USEPOLLING: "1"
      WATCHPACK_POLLING: "true"
    volumes:
      - .:/app
      - expo-node-modules:/app/node_modules
      - expo-dot-expo:/app/.expo
    command: npm run start -- --lan --port 8081
    tty: true
    stdin_open: true

volumes:
  expo-node-modules:
  expo-dot-expo:
